### ISSUE TITLE
Add discover tags and automatic build support

### ISSUE THREAD

**Issue by tanandy** [OpenPaaS-Suite/CI-jobs#10]
https://github.com/OpenPaaS-Suite/CI-jobs/blob/0dc731c645474aa1ee0a39ee8c49358740a4987c/CreateJobs.groovy#L29

![image](https://user-images.githubusercontent.com/18187444/98038775-fb10d000-1e1d-11eb-9997-47f80e7dbea3.png)

we would like to have the ability to keep discover tags + build strategies for tags on default jobs.

Or we must be able to make specific configuration per job

WDYT  @aduprat 

cc @thebtililya

**Comment by aduprat** [comment]
All in one is more simple for the newcomers in order to understand the pipeline, IMHO.

**Comment by tanandy** [comment]
alright do you get the right syntax for it?

**Comment by aduprat** [comment]
You can try to follow such syntax:
http://markferry.net/pmwiki/pmwiki.php?n=Tech.JenkinsMultibranchPipelineWithGitTagDiscovery

**Comment by tanandy** [comment]
Fixed in https://github.com/OpenPaaS-Suite/CI-jobs/commit/0984add2894c1e16f6fe819c1dbd247c575d4190
